from datetime import datetime, timezone
from enum import IntEnum, StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class AgentResultStatus(IntEnum):
    SUCCESS_WITH_DATA = 100
    SUCCESS_WITHOUT_DATA = 101

    # Agent API and task routing
    AGENT_SERVICE_UNAVAILABLE = 400
    AGENT_SERVICE_TIMEOUT = 401
    AGENT_EXECUTION_FAILED = 402
    AGENT_TASK_UNSUPPORTED = 403
    AGENT_REQUEST_CONTRACT_INVALID = 404

    # Model provider and model output
    LLM_PROVIDER_UNAVAILABLE = 410
    LLM_AUTHENTICATION_FAILED = 411
    LLM_RATE_LIMITED = 412
    LLM_REQUEST_TIMEOUT = 413
    LLM_EMPTY_RESPONSE = 414
    LLM_TOOL_CALL_MALFORMED = 415
    LLM_OUTPUT_SCHEMA_INVALID = 416
    LLM_CONTENT_REJECTED = 417
    LLM_CONTEXT_LIMIT_EXCEEDED = 418
    LLM_PROVIDER_INTERNAL_ERROR = 419

    # Tool execution
    TOOL_NOT_REGISTERED = 420
    TOOL_NOT_AUTHORIZED = 421
    TOOL_ARGUMENT_INVALID = 422
    TOOL_EXECUTION_TIMEOUT = 423
    TOOL_EXECUTION_FAILED = 424
    TOOL_RESULT_INVALID = 425
    TOOL_DEPENDENCY_UNAVAILABLE = 426

    # Memory and session state
    MEMORY_SERVICE_UNAVAILABLE = 430
    MEMORY_READ_FAILED = 431
    MEMORY_WRITE_FAILED = 432
    MEMORY_SERIALIZATION_FAILED = 433
    MEMORY_VERSION_CONFLICT = 434
    MEMORY_LOCK_UNAVAILABLE = 435
    MEMORY_RECORD_NOT_FOUND = 436

    # RAG and document processing
    RAG_SERVICE_UNAVAILABLE = 440
    RAG_RETRIEVAL_FAILED = 441
    RAG_EMBEDDING_FAILED = 442
    RAG_VECTOR_STORE_FAILED = 443
    RAG_INDEXING_FAILED = 444
    RAG_DELETION_FAILED = 445
    RAG_DOCUMENT_PARSE_FAILED = 446
    RAG_DOCUMENT_TOO_LARGE = 447
    RAG_NO_RELEVANT_DOCUMENT = 448

    # Shared infrastructure
    REDIS_UNAVAILABLE = 450
    REDIS_OPERATION_TIMEOUT = 451
    RABBITMQ_UNAVAILABLE = 452
    RABBITMQ_PUBLISH_FAILED = 453
    RABBITMQ_CONSUME_FAILED = 454
    RABBITMQ_MESSAGE_INVALID = 455

    # Agent runtime and workflow
    AGENT_SESSION_NOT_FOUND = 460
    AGENT_SESSION_CONCURRENCY_CONFLICT = 461
    AGENT_SESSION_STATE_INVALID = 462
    AGENT_STATE_PERSISTENCE_FAILED = 463
    AGENT_RUN_CANCELLED = 464
    AGENT_RUN_STEP_LIMIT_EXCEEDED = 465
    AGENT_RUN_DEADLINE_EXCEEDED = 466

    # Configuration, Skills and other external sources
    AGENT_CONFIGURATION_INVALID = 470
    AGENT_PROMPT_NOT_FOUND = 471
    AGENT_SKILL_NOT_FOUND = 472
    AGENT_SKILL_CONFIGURATION_INVALID = 473
    EXTERNAL_WEB_REQUEST_FAILED = 474
    EXTERNAL_WEB_CONTENT_UNSAFE = 475
    RESUME_DOCUMENT_PARSE_FAILED = 476
    RESUME_ANALYSIS_FAILED = 477
    RESUME_ANALYSIS_NOT_FOUND = 478
    AGENT_INTERNAL_ERROR = 499


class AgentTaskType(StrEnum):
    CONVERSATION = "CONVERSATION"
    RESUME_ANALYSIS = "RESUME_ANALYSIS"
    RESUME_MEMORY_ACTIVATION = "RESUME_MEMORY_ACTIVATION"
    INTERVIEW_SESSION_INITIALIZATION = "INTERVIEW_SESSION_INITIALIZATION"
    INTERVIEW_SESSION_COMPLETION = "INTERVIEW_SESSION_COMPLETION"
    INTERVIEW_SESSION_CLOSE = "INTERVIEW_SESSION_CLOSE"
    INTERVIEW_SESSION_PAUSE = "INTERVIEW_SESSION_PAUSE"
    INTERVIEW_TURN = "INTERVIEW_TURN"
    INTERVIEW_ACTION = "INTERVIEW_ACTION"
    RAG_DOCUMENT_INDEXING = "RAG_DOCUMENT_INDEXING"
    RAG_DOCUMENT_DELETION = "RAG_DOCUMENT_DELETION"
    RAG_DOCUMENT_DOWNLOAD = "RAG_DOCUMENT_DOWNLOAD"
    RAG_DOCUMENT_INDEX_STATUS = "RAG_DOCUMENT_INDEX_STATUS"
    RESUME_DOCUMENT_UPLOAD = "RESUME_DOCUMENT_UPLOAD"
    RESUME_ANALYSIS_STATUS = "RESUME_ANALYSIS_STATUS"
    RESUME_REANALYZE = "RESUME_REANALYZE"
    RESUME_DOCUMENT_DOWNLOAD = "RESUME_DOCUMENT_DOWNLOAD"
    RESUME_DOCUMENT_DELETION = "RESUME_DOCUMENT_DELETION"
    WEB_PAGE_FETCH = "WEB_PAGE_FETCH"
    WEBSITE_CRAWL = "WEBSITE_CRAWL"
    URL_KNOWLEDGE_BASE_CRAWL = "URL_KNOWLEDGE_BASE_CRAWL"
    URL_KNOWLEDGE_BASE_IMPORT = "URL_KNOWLEDGE_BASE_IMPORT"
    URL_KNOWLEDGE_BASE_ARCHIVE = "URL_KNOWLEDGE_BASE_ARCHIVE"
    RESUME_MEMORY_DELETION = "RESUME_MEMORY_DELETION"
    INTERVIEW_MEMORY_DELETION = "INTERVIEW_MEMORY_DELETION"


class AgentError(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    type: str
    message: str
    retryable: bool = False


class AgentOperationResponse(BaseModel):
    """独立 Agent 对外返回的通用结果，不携带调用方业务任务枚举。"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    api_version: str = Field(alias="apiVersion")
    request_id: str = Field(alias="requestId")
    run_id: str = Field(alias="runId")
    principal_id: str = Field(alias="principalId")
    conversation_id: str = Field(alias="conversationId")
    task_type: AgentTaskType = Field(
        default=AgentTaskType.CONVERSATION,
        exclude=True,
    )
    status_code: AgentResultStatus = Field(alias="statusCode")
    status: Literal["COMPLETED", "PROCESSING", "FAILED"]
    state_version: int = Field(alias="stateVersion", ge=0)
    data: dict[str, Any] | None = None
    error: AgentError | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
