import { useCallback, useEffect, useState } from 'react';
import { FileText, Loader2, RefreshCw, Trash2, Upload } from 'lucide-react';
import { historyApi, type ResumeListItem } from '../api/history';
import DeleteConfirmDialog from '../components/DeleteConfirmDialog';
import { formatDateOnly } from '../utils/date';

export default function HistoryPage({ onSelectResume }: { onSelectResume: (id: string) => void }) {
  const [resumes, setResumes] = useState<ResumeListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [pendingDelete, setPendingDelete] = useState<ResumeListItem | null>(null);
  const [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setResumes(await historyApi.getResumes()); setError(''); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : '加载简历失败'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!resumes.some(item => item.analyzeStatus === 'PENDING' || item.analyzeStatus === 'PROCESSING')) return; const timer = window.setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [resumes, load]);
  const remove = async () => { if (!pendingDelete) return; setDeleting(true); try { await historyApi.deleteResume(pendingDelete.id); setPendingDelete(null); await load(); } finally { setDeleting(false); } };
  const reanalyze = async (resume: ResumeListItem) => { const targetRole = window.prompt('请输入目标岗位'); if (!targetRole?.trim()) return; await historyApi.reanalyze(resume.id, targetRole.trim()); await load(); };
  return <main className="mx-auto max-w-5xl"><header className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-800 dark:text-white">简历管理</h1><p className="mt-1 text-sm text-slate-500">上传、浏览与分析当前和历史版本简历。</p></div><a href="/upload" className="inline-flex items-center gap-2 rounded-xl bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white"><Upload className="h-4 w-4" />上传简历</a></header>{loading ? <div className="flex min-h-[30vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary-500" /></div> : error ? <p className="text-sm text-red-500">{error}</p> : resumes.length === 0 ? <div className="rounded-2xl bg-white p-12 text-center dark:bg-slate-800"><FileText className="mx-auto h-10 w-10 text-slate-400" /><p className="mt-3 text-slate-500">暂无简历。</p></div> : <div className="space-y-3">{resumes.map(resume => <article key={resume.id} className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-800"><button onClick={() => onSelectResume(resume.id)} className="min-w-0 flex-1 text-left"><span className="block truncate font-medium text-slate-800 dark:text-white">{resume.filename ?? '未命名简历'}</span><span className="mt-1 block text-sm text-slate-500">{formatDateOnly(resume.uploadedAt)} · {resume.interviewCount} 场文本面试 · {resume.analyzeStatus ?? 'PENDING'}</span></button><div className="text-right"><span className="text-sm font-semibold text-slate-700 dark:text-slate-200">{resume.latestScore ?? '-'}</span><span className="ml-1 text-xs text-slate-400">分析分</span></div><div className="flex gap-1">{resume.analyzeStatus === 'FAILED' && <button onClick={() => void reanalyze(resume)} className="rounded-lg p-2 text-slate-400 hover:bg-primary-50 hover:text-primary-500" title="重新分析"><RefreshCw className="h-5 w-5" /></button>}<button onClick={() => setPendingDelete(resume)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-500" title="删除"><Trash2 className="h-5 w-5" /></button></div></article>)}</div>}<DeleteConfirmDialog open={pendingDelete !== null} item={pendingDelete ? { id: pendingDelete.id, name: String(pendingDelete.filename ?? pendingDelete.id) } : null} itemType="简历" loading={deleting} onConfirm={() => void remove()} onCancel={() => setPendingDelete(null)} /></main>;
}
